# Setup
title:            Zoru.co
tagline:          'ASMR and stuff'
descriptionEN:    'Personal website of Zoru, student and content producer'
descriptionFR:    'Site web personel de Zoru, étudiant et créateur de contenu'
url:              http://zoru.co
baseurl:          ""

# Includes an icon in the footer for each username you enter
socialLinks:
  email: zoruasmr@gmail.com
  facebook: https://www.facebook.com/Zoruasmr/
  github: https://github.com/zoruninho
  instagram: https://www.instagram.com/zoruasmr/
  linkedin: pfacq
  twitter: https://twitter.com/Zoruasmr
  youtube: https://www.youtube.com/user/Zoruasmr

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-45012883-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.zoru.co

#Language configuration
defaults:
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
      layout: "post"
  -
    scope:
      path: "_posts/fr"
    values:
      lang: "fr"
      layout: "post"
  -
    scope:
      path: "pages/fr"
    values:
      lang: "fr"
      layout: "page"
  -
    scope:
      path: "pages/en"
    values:
      lang: "en"
      layout: "page"


# Dependencies

markdown: kramdown
  
highlighter: rouge

# Permalinks

permalink: /:categories/:title

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate #enables pagination

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
