# Site wide configuration

title: "Bientôt !"
description: "Site personnel de Zoru"
#if you modify locale please have a look at _data/messages.yml too
locale: fr
#for meta name="author" :
author: Zoru

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2020
  month: 1
  day: 1
  hour: 0
  minute: 0

# Site owner
owner:
  name: Zoru
  email: zoruasmr@gmail.com
  twitter: https://twitter.com/Zoruninho
  google-plus:
  instagram: https://www.instagram.com/zoru_insta/
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url:
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
